name: Build and Release

on:
  push:
    tags:
      - '**'

jobs:
  run-script-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: |
          bundle install --without development

      - name: Lint flight plans
        run: bin/lint-flight-plans

      - name: Create path-safe tag name
        run: echo "SAFE_TAG_NAME=$(echo ${{ github.ref_name }} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Make release artifacts
        run: |
          bin/make-release ${{ env.SAFE_TAG_NAME }}
          bin/zip-outputs ${{ env.SAFE_TAG_NAME }}

      - name: Create and upload release
        run: |
          gh release create ${{ github.ref_name }} json-outputs-${{ env.SAFE_TAG_NAME }}.zip \
            --title ${{ env.SAFE_TAG_NAME }}
        env:
          GH_TOKEN: ${{ github.token }}
